# -*- coding: utf-8 -*-
"""BMI CALCULATOR

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fJBJfAJDJusa36vhyeYXXKDNxIc3KGs8
"""

height = float(input("Enter your height in cm: "))
weight = float(input("Enter your weight in kg: "))

BMI = weight / (height/100)**2

print("Your BMI is",BMI)

if BMI <= 18.4:
    print("You are underweight!! Eat well.")
elif BMI <= 24.9:
    print("You are healthy.Be fit as you are now")
elif BMI <= 29.9:
    print("You are over weight.Avoid junk foods")
elif BMI <= 34.9:
    print("You are severely over weight.Plan jogging")
elif BMI <= 39.9:
    print("You are obese.Plan your diet")
else:
    print("You are severely obese.Please visit dietician")

